name: IllyriaUtils
main: eu.illyrion.illyriautils.Plugin
version: 0.0.1-SNAPSHOT
api-version: 1.15
authors:
  - gaia-03
  - IllyrionSoftware
database: false
load: POSTWORLD
commands:
  iutils:
    description: Reloads the configuration
    permission: iutils.reload
    usage: /<command>
