name: ${project.name}
description: ${project.description}
main: ${project.main}
version: ${project.version}
api-version: ${project.api.version}
authors: ${project.authors}
load: ${project.load}
commands:
  iutils:
    description: Reloads the configuration
    permission: illyriautils.reload
    usage: /<command>
permissions:
  illyriautils.reload:
    description: Allows the player to reload the configuration
    default: op
